'use strict';
const $=id=>document.getElementById(id);
const token=document.querySelector('meta[name="astra-token"]').content;
let state=null, selectedRun=null, selectedStep='latest', view='live', pending=false, toastTimer, lastConsole='', imageCycle=0, initialized=false;
const roles=['左腕相机','桌面相机','俯视相机','附加视角'];
const names={scene_assessment:'当前场景',previous_result_assessment:'上一步结果',next_action_intent:'下一步意图',expected_visible_change:'预期可见变化'};
function text(id,value){$(id).textContent=value;}
function toast(message){text('toast',message);$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,5500);}
async function post(path,body={}){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-Astra-Token':token},body:JSON.stringify(body)});let data;try{data=await r.json();}catch{throw new Error('请求未被服务接受（'+r.status+'）');}if(!r.ok)throw new Error(data.error||'请求失败');return data;}
function settings(){return {profile:$('profile').value,mode:$('mode').value,task:$('task').value,max_steps:Number($('max-steps').value),wall_budget_s:Number($('budget').value),phase:$('phase').value,layout_id:$('layout').value,trial_id:$('trial').value,preview_port:8765};}
function applySettings(s){const ids={profile:'profile',mode:'mode',task:'task',max_steps:'max-steps',wall_budget_s:'budget',phase:'phase',layout_id:'layout',trial_id:'trial'};for(const [key,id] of Object.entries(ids))if(s[key]!==undefined)$(id).value=s[key];condition();}
function condition(){const p=$('profile').value;const d=p.endsWith('D1');text('condition-description',p.startsWith('legacy')?'保留原始反馈格式 · '+(p==='legacy4'?'四':'三')+'张模型输入图':p[1]+' 条真实历史 · '+(d?'公开诊断':'原始动作输出')+' · 三张模型输入图');if(state&&!state.demo){text('environment-badge',$('mode').value==='execute'?'REAL HARDWARE · 真机执行':'SHADOW · 仅观察');$('environment-badge').className='pill '+($('mode').value==='execute'?'warn':'');}}
function download(value,name){const blob=new Blob([JSON.stringify(value,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
for(let i=0;i<4;i++){
 const card=document.createElement('article');card.className='camera-card offline';card.id='camera-'+i;
 const top=document.createElement('div');top.className='camera-top';const name=document.createElement('div');name.className='camera-name';const num=document.createElement('span');num.className='camera-index';num.textContent='0'+(i+1);name.append(num,document.createTextNode(roles[i]));const tag=document.createElement('span');tag.className='camera-tag';tag.id='camera-tag-'+i;top.append(name,tag);
 const img=document.createElement('img');img.id='camera-image-'+i;img.alt=roles[i]+'画面';img.hidden=true;img.loading='eager';
 const placeholder=document.createElement('div');placeholder.className='camera-placeholder';placeholder.id='camera-placeholder-'+i;const icon=document.createElement('div');icon.className='placeholder-icon';icon.textContent='▧';const title=document.createElement('span');title.id='camera-empty-title-'+i;title.textContent='等待视频流';const detail=document.createElement('small');detail.id='camera-error-'+i;placeholder.append(icon,title,detail);
 const bottom=document.createElement('div');bottom.className='camera-bottom';const serial=document.createElement('span');serial.id='camera-serial-'+i;const age=document.createElement('span');age.id='camera-age-'+i;bottom.append(serial,age);card.append(img,placeholder,top,bottom);$('camera-grid').append(card);
 img.addEventListener('load',()=>{img.hidden=false;placeholder.hidden=true;card.classList.remove('offline');});
 img.addEventListener('error',()=>{img.hidden=true;placeholder.hidden=false;card.classList.add('offline');text('camera-empty-title-'+i,view==='decision'?'该决策没有此路图像':'画面暂不可用');});
}
function activeStep(){if(!state)return null;return state.steps.find(s=>s.step===selectedStep)||state.latest;}
function renderCameras(refreshImages=false){if(!state)return;const step=activeStep();const count=state.camera_status.filter(c=>c.available).length;text('camera-count',view==='live'?count+' / 4':'观测存档');text('camera-hint',view==='live'?'按已连接机位显示；模型输入视角保持实验配置。':(state.selected_run&&step?.step?'仅显示 '+step.step+' 决策图 · '+(step.observation_id||'观测 ID 缺失'):'选择一个已有决策查看输入图片。'));
 for(let i=0;i<4;i++){const c=state.camera_status[i];const img=$('camera-image-'+i);text('camera-serial-'+i,c?.serial||'未配置');text('camera-age-'+i,view==='decision'?(step?.decision_cameras?.[i]?.captured_at ? new Date(step.decision_cameras[i].captured_at*1000).toLocaleTimeString():'缺少时间戳'):c?.available?(state.demo?'DEMO':c.age_s+'s ago'):'OFFLINE');const modelInput=view==='decision'?Boolean(step?.decision_cameras?.[i]):i<((state.active?state.settings.profile:$('profile').value)==='legacy4'?4:3);text('camera-tag-'+i,(view==='decision'?'RECORDED':state.demo?'DEMO':c?.available?'LIVE':'OFFLINE')+' · '+(modelInput?'模型输入':'仅预览')); $('camera-tag-'+i).className='camera-tag '+(state.demo||view==='decision'?'demo':'');
 const available=view==='decision'?Boolean(state.selected_run&&step?.step):c?.available;
 if(!available){img.removeAttribute('src');img.hidden=true;$('camera-placeholder-'+i).hidden=false;$('camera-'+i).classList.add('offline');text('camera-empty-title-'+i,view==='decision'?'尚无决策图像':'相机未就绪');text('camera-error-'+i,c?.error||'连接后会自动显示');continue;}
 if(refreshImages){text('camera-error-'+i,'');img.src=view==='live'?'/api/camera/'+i+'?v='+imageCycle:'/api/history-image?'+new URLSearchParams({run:state.selected_run,step:step.step,index:i,v:imageCycle});}
 }}
function renderStep(){const s=activeStep()||{};text('step-status',s.stage||'等待开始');const diag=s.diagnostics||{};const assessment=$('assessment');assessment.replaceChildren();if(Object.keys(diag).length){assessment.className='assessment';for(const [key,label] of Object.entries(names)){const section=document.createElement('section');section.className='diagnostic';const h=document.createElement('h3');h.textContent=label+' · 模型判断';const p=document.createElement('p');p.textContent=diag[key]||'unknown';section.append(h,p);assessment.append(section);}}else{assessment.className='assessment empty';const icon=document.createElement('div');icon.className='empty-symbol';icon.textContent='✳';const h=document.createElement('h3');h.textContent=s.step?'尚无公开诊断':'等待第一条观测';const p=document.createElement('p');p.textContent=s.step?'D0 与 legacy 不输出诊断；D1 会在模型返回后显示。此处不补写模型的内部推理。':'开始实验后，这里会显示场景判断、动作意图和执行反馈。';assessment.append(icon,h,p);}
 text('action-text',s.action_summary?.text||'尚无动作');$('action-chips').replaceChildren();if(s.action_summary?.translation_mm){for(const [i,v]of s.action_summary.translation_mm.entries()){const span=document.createElement('span');span.textContent='XYZ'[i]+' '+(v>=0?'+':'')+v+' mm';$('action-chips').append(span);}if(s.action_summary.opening_percent!==null){const span=document.createElement('span');span.textContent='夹爪 → '+s.action_summary.opening_percent+'%';$('action-chips').append(span);}}
 const summary=state.summary;const aborted=summary.status==='STOPPED'&&s.step===state.latest?.step&&s.status==='WAITING';text('result-title',aborted?'回合已停止 · 本步未执行':s.result_text||'等待执行');const reason=s.failure_reason||(summary.status==='STOPPED'?summary.reason:null);text('result-reason',reason|| (s.hardware_commands_sent!==undefined&&s.hardware_commands_sent!==null?(state.selected_synthetic?'本步模拟下发 ':'本步下发 ')+s.hardware_commands_sent+' 个通道。球的位置和抓放结果仍需独立观察。':'模型提案通过解析、状态与 IK 检查后，才会交给原执行器。'));$('result-card').className='result-card '+(reason||['STOPPED','REJECTED_IK','FAILED','CHECK_ERROR'].includes(s.status)?'fail':'');text('execution-detail',JSON.stringify({actually_sent:s.executed_command||null,sdk_return:s.sdk_result||null,feasibility:s.feasibility||null},null,2));
 const fmt=v=>Array.isArray(v)?v.map(x=>(x>=0?'+':'')+x.toFixed(1)).join(' / '):'—';text('actual-delta',fmt(s.actual_xyz_delta_mm));text('residual',fmt(s.translation_residual_mm));text('gripper-feedback',typeof s.gripper_after?.position==='number'?(s.gripper_after.position/10).toFixed(1)+'%':'—');text('telemetry-label',(s.step||'等待')+' · 执行后回读');
 const stable=state.independent_success;text('outcome-title',stable===true?'Success · 独立观察确认入框':stable===false?'Fail · 独立观察确认未完成':'任务成功：尚未独立确认');text('outcome-note',stable==='unknown'?'SDK 成功或模型 done，不自动代表球已稳定落框。':state.labels.notes||state.labels.evidence||'已保存独立观察证据。');
 $('annotate').disabled=!state.selected_run||(state.active&&state.selected_run===state.current_run);
}
function render(){const s=state;if(!initialized){if(s.active)applySettings(s.settings);initialized=true;}text('run-count',s.runs.length);$('connection-dot').className='status-dot ok';text('connection-text','控制台已连接');$('demo-camera-control').hidden=!s.demo;if(s.demo){text('environment-badge','SYNTHETIC · 无硬件演示');$('environment-badge').className='pill warn';text('start','▶ 开始演示');$('demo-camera-count').value=String(s.camera_status.filter(c=>c.available).length);}else{condition();text('start',$('mode').value==='execute'?'▶ 开始真机实验':'▶ 开始 Shadow');}
 if(s.cameras_only){$('controls').hidden=true;document.querySelector('.decision-column').hidden=true;document.querySelector('.workspace').style.gridTemplateColumns='1fr';text('environment-badge',s.demo?'相机预览 · 演示':'相机预览 · 只读');}
 $('rescan').disabled=s.active||pending;$('start').disabled=s.active||pending;$('stop').disabled=!s.active||s.stop_requested||pending;text('stop',s.stop_requested?'停止请求已发送':'■ 停止本回合');
 for(const id of ['task','profile','mode','max-steps','budget','phase','layout','trial','import-config','single-shadow','pair-plan'])$(id).disabled=s.active;
 const current=s.selected_run===s.current_run;const inProgress=s.active&&current;let runStatus=inProgress?(s.stop_requested?'等待停止':'运行中'):s.summary.status==='MODEL_DONE'?'模型宣称完成':s.summary.status==='STOPPED'?(String(s.summary.reason).includes('HUMAN_STOP')?'人工停止':'FAIL · 已停止'):s.summary.status==='MAX_STEPS'?'达到步数上限':s.summary.status==='WALL_BUDGET_EXHAUSTED'?'预算耗尽':s.selected_run?'已结束':'尚未开始';if(s.budget_expired&&current&&!s.active)runStatus='预算耗尽';text('run-status',runStatus);$('run-status').className='pill '+(s.summary.status==='STOPPED'?'error':s.summary.status==='MAX_STEPS'||s.summary.status==='WALL_BUDGET_EXHAUSTED'?'warn':'');
 const limit=s.profile.max_steps||s.settings.max_steps||10;$('step-metric').replaceChildren(document.createTextNode(String(s.steps.length||'—')+' '));const total=document.createElement('span');total.textContent='/ '+limit;$('step-metric').append(total);text('calls-metric',s.summary.model_calls??(s.demo?'0':s.steps.filter(x=>x.backend?.backend==='CodexAstraBackend').length));const seconds=inProgress?(Date.now()/1000-s.started_at):(s.summary.episode_total_s||0);text('elapsed-metric',String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(Math.floor(seconds%60)).padStart(2,'0'));
 const pick=$('step-select');const signature=s.steps.map(x=>x.step).join(',');if(pick.dataset.signature!==signature){pick.dataset.signature=signature;pick.replaceChildren(new Option('跟随最新步骤','latest'));s.steps.forEach(x=>pick.append(new Option(x.step,x.step)));if(!s.steps.some(x=>x.step===selectedStep))selectedStep='latest';pick.value=selectedStep;}
 text('log-path','LOG · '+(s.run_path||'尚未生成日志'));$('log-path').title=s.run_path||'';$('export-report').disabled=!s.selected_run;
 const newConsole=s.console.join('\n');if(newConsole!==lastConsole){const panel=$('console-panel');const nearBottom=panel.scrollHeight-panel.scrollTop-panel.clientHeight<70;lastConsole=newConsole;text('console-output',newConsole||'等待进程输出…');if(nearBottom)panel.scrollTop=panel.scrollHeight;}
 const err=s.error||(!inProgress&&s.summary.status==='STOPPED'?s.summary.reason:null);$('notice').hidden=!err;if(err)text('notice',err);renderStep();renderCameras();
}
async function poll(){try{const r=await fetch('/api/state'+(selectedRun?'?run='+encodeURIComponent(selectedRun):''));const data=await r.json();if(!r.ok)throw new Error(data.error);state=data;render();}catch(err){$('connection-dot').className='status-dot';text('connection-text','连接中断 · 自动重试');$('notice').hidden=false;text('notice',String(err.message||err));$('start').disabled=true;}finally{setTimeout(poll,700);}}
$('experiment-form').addEventListener('submit',async e=>{e.preventDefault();if(pending)return;pending=true;$('start').disabled=true;try{await post('/api/start',settings());selectedRun=null;selectedStep='latest';view='live';updateView();toast(state?.demo?'演示已启动，不调用模型或硬件。':'实验已启动，任务将自动闭环执行。');}catch(err){toast(err.message);}finally{pending=false;}});
$('stop').addEventListener('click',async()=>{try{await post('/api/stop');toast('停止请求已发送，正在等待当前调用返回。');}catch(err){toast(err.message);}});
$('profile').addEventListener('change',condition);$('mode').addEventListener('change',()=>{condition();if(state)render();});
$('advanced-toggle').addEventListener('click',()=>{$('advanced').hidden=!$('advanced').hidden;$('advanced-toggle').setAttribute('aria-expanded',String(!$('advanced').hidden));});
$('save-config').addEventListener('click',()=>download(settings(),'astra-experiment.json'));
$('import-config').addEventListener('change',async e=>{try{const file=e.target.files[0];if(!file)return;const s=JSON.parse(await file.text());if(!s||typeof s!=='object'||Array.isArray(s))throw new Error('配置必须为 JSON 对象');applySettings(s);toast('配置已载入；开始前可继续修改。');}catch(err){toast(err.message);}finally{e.target.value='';}});
function updateView(){$('view-live').classList.toggle('selected',view==='live');$('view-decision').classList.toggle('selected',view==='decision');imageCycle++;renderCameras(true);}
$('view-live').addEventListener('click',()=>{view='live';updateView();});$('view-decision').addEventListener('click',()=>{view='decision';updateView();});$('step-select').addEventListener('change',e=>{selectedStep=e.target.value;view='decision';renderStep();updateView();});
$('rescan').addEventListener('click',async()=>{try{await post('/api/rescan');toast('正在重新检测相机；已有实验结果保持不变。');}catch(err){toast(err.message);}});
$('demo-camera-count').addEventListener('change',async e=>{try{await post('/api/demo-cameras',{count:Number(e.target.value)});}catch(err){toast(err.message);}});
for(const tab of ['summary','console'])$('tab-'+tab).addEventListener('click',()=>{for(const name of ['summary','console']){$(name+'-panel').hidden=name!==tab;$('tab-'+name).setAttribute('aria-selected',String(name===tab));}});
$('history-toggle').addEventListener('click',()=>{const list=$('history-list');list.replaceChildren();for(const r of state?.runs||[]){const b=document.createElement('button');b.className='history-item';const left=document.createElement('div');const title=document.createElement('strong');title.textContent=r.profile+(r.synthetic?' · SYNTHETIC':'');const subtitle=document.createElement('small');subtitle.textContent=r.id;left.append(title,subtitle);const badge=document.createElement('span');badge.className='pill '+(r.status==='STOPPED'?'error':'');badge.textContent=r.status;b.append(left,badge);b.addEventListener('click',()=>{selectedRun=r.id;selectedStep='latest';view='decision';$('history-dialog').close();updateView();});list.append(b);}if(!list.children.length){const p=document.createElement('p');p.className='muted';p.textContent='暂无实验记录。';list.append(p);}$('history-dialog').showModal();});
$('return-live').addEventListener('click',()=>{selectedRun=null;selectedStep='latest';view='live';$('history-dialog').close();updateView();});
for(const b of document.querySelectorAll('[data-close]'))b.addEventListener('click',()=>$(b.dataset.close).close());
$('annotate').addEventListener('click',()=>{text('annotation-run',(state.selected_synthetic?'SYNTHETIC 演示记录 · ':'')+state.selected_run);$('annotation-dialog').dataset.run=state.selected_run;$('observer').value=state.labels.observer||'';$('evidence').value=state.labels.evidence||'';$('reason').value=state.labels.notes||'';$('label-result').value=state.independent_success===true?'success':state.independent_success===false?'fail':'unknown';$('annotation-dialog').showModal();});
$('annotation-form').addEventListener('submit',async e=>{e.preventDefault();try{await post('/api/annotate',{run:$('annotation-dialog').dataset.run,result:$('label-result').value,observer:$('observer').value,evidence:$('evidence').value,reason:$('reason').value});$('annotation-dialog').close();toast('独立观察已保存；不会回灌模型。');}catch(err){toast(err.message);}});
$('export-report').addEventListener('click',async()=>{try{const r=await fetch('/api/export?run='+encodeURIComponent(state.selected_run));const data=await r.json();if(!r.ok)throw new Error(data.error);download(data,state.selected_run+'-report.json');}catch(err){toast(err.message);}});
setInterval(()=>{text('clock',new Date().toLocaleTimeString('zh-CN',{hour12:false}));if(state&&!document.hidden){imageCycle++;renderCameras(true);}},900);condition();poll();

$('preflight').addEventListener('click',async()=>{try{const data=await post('/api/preflight',settings());$('equivalent-command').value=data.command;delete data.command;text('preflight-result',JSON.stringify(data,null,2));$('preflight-dialog').showModal();}catch(e){toast(e.message);}});
$('copy-command').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('equivalent-command').value);toast('命令已复制。');}catch{toast('请从文本框手动复制命令。');}});
$('single-shadow').addEventListener('click',async()=>{if(pending)return;pending=true;try{await post('/api/start',{...settings(),mode:'shadow',max_steps:1});selectedRun=null;selectedStep='latest';view='live';updateView();toast('单次 Shadow 已启动；不下发动作，原配置保持。');}catch(e){toast(e.message);}finally{pending=false;}});
$('pair-plan').addEventListener('change',e=>{if(!e.target.value)return;const [layout,profile]=e.target.value.split(',');$('layout').value=layout;$('profile').value=profile;$('phase').value='placement';condition();toast('已载入 '+layout+' / '+profile+'。请人工复位场景后启动。');});

let replayData=null;
async function getJSON(url){const r=await fetch(url);const d=await r.json();if(!r.ok)throw new Error(d.error);return d;}
function replayQuery(){return new URLSearchParams({run:replayData.run,step:replayData.step});}
function renderReplay(){if(!replayData)return;const d=replayData;const stage=$('replay-stage').value;text('replay-heading',(d.synthetic?'SYNTHETIC · ':'')+d.run+' / '+d.step);text('replay-warning',[d.note,...d.warnings].join(' · '));const t=d.facts.transition||{};text('replay-action','实际下发通道：'+(t.hardware_commands_sent??d.facts.execution.hardware_commands_sent??'缺少记录')+' · '+(t.execution_status||d.facts.execution.status||'unknown')+' · TCP 实测 Δ(m)：'+JSON.stringify(t.actual_xyz_delta_m??null)+' · 夹爪回读：'+JSON.stringify(t.gripper_after?.position??null));text('replay-facts',JSON.stringify(d.facts,null,2));text('replay-markers',d.markers.length?JSON.stringify(d.markers,null,2):'此步骤尚无人工关键时刻标记。');$('replay-pairs').replaceChildren();for(const pair of d.pairs){const row=document.createElement('div');row.className='replay-pair';for(const side of [stage,'after']){const figure=document.createElement('figure');const item=pair[side];const label=document.createElement('figcaption');label.textContent=pair.role+' / '+pair.serial+' · '+(side==='before'?'动作前':side==='decision'?'决策输入':'动作后');figure.append(label);if(item?.available){const img=document.createElement('img');img.alt=label.textContent;img.src='/api/replay-image?'+new URLSearchParams({run:d.run,step:d.step,serial:pair.serial,role:pair.role,stage:side});figure.append(img);}else{const gap=document.createElement('p');gap.className='replay-gap';gap.textContent='缺失 / 校验失败：'+(item?.errors?.join(', ')||'没有本步记录');figure.append(gap);}const meta=document.createElement('small');meta.textContent=item?[item.observation_id,(Number.isFinite(item.captured_at)?new Date(item.captured_at*1000).toISOString():'时间缺失'),item.width+' × '+item.height,'SHA '+item.sha256,item.errors.join(', ')].join(' · '):'不补图、不替换为相邻步骤';figure.append(meta);row.append(figure);}$('replay-pairs').append(row);}}
$('open-replay').addEventListener('click',async()=>{try{const step=activeStep();if(!state?.selected_run||!step?.step)throw new Error('请先选择一个已有步骤。');replayData=await getJSON('/api/replay?'+new URLSearchParams({run:state.selected_run,step:step.step}));$('control-annotation').value='';text('controls-result','');$('prepared-download').hidden=true;renderReplay();$('replay-dialog').showModal();}catch(e){toast(e.message);}});
$('replay-stage').addEventListener('change',renderReplay);
$('export-evidence').addEventListener('click',async()=>{try{const r=await fetch('/api/evidence-zip?'+replayQuery());if(!r.ok)throw new Error((await r.json()).error);const a=document.createElement('a');a.href=URL.createObjectURL(await r.blob());a.download=replayData.run+'-'+replayData.step+'-evidence.zip';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}catch(e){toast(e.message);}});
$('marker-form').addEventListener('submit',async e=>{e.preventDefault();try{await post('/api/marker',{run:replayData.run,step:replayData.step,kind:$('marker-kind').value,observer:$('marker-observer').value,evidence:$('marker-evidence').value});replayData=await getJSON('/api/replay?'+replayQuery());renderReplay();toast('事后标记已保存，不回灌模型。');}catch(e){toast(e.message);}});
$('load-control-template').addEventListener('click',async()=>{try{$('control-annotation').value=JSON.stringify(await getJSON('/api/control-template?'+replayQuery()),null,2);}catch(e){toast(e.message);}});
async function prepareOffline(history){try{const payload={run:replayData.run,step:replayData.step,base_profile:$('control-profile').value};if(history){payload.visual_history_mode='previous_fixed_before';payload.fixed_camera=$('fixed-camera').value;}else payload.annotation=JSON.parse($('control-annotation').value);text('controls-result','准备中…');const result=await post('/api/prepare-controls',payload);text('controls-result',JSON.stringify(result,null,2));const link=$('prepared-download');link.href='/api/prepared-zip?'+new URLSearchParams({id:result.output.split('/').pop()});link.download='prepared-evidence.zip';link.hidden=false;toast('离线输入已准备；模型调用 0，硬件调用 0。');}catch(e){text('controls-result',e.message);}}
$('prepare-controls').addEventListener('click',()=>prepareOffline(false));$('prepare-visual-history').addEventListener('click',()=>prepareOffline(true));
